modLoader = "javafml"
loaderVersion = "${loader_version_range}"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "fogoverrides"
version = "${version}"
displayName = "Fog Overrides"
authors = "fabbe50"
description = '''
Mod to make fog do what you want.
'''
logoFile = "assets/fogoverrides/icon.png"

[[mixins]]
config = "fogoverrides.mixins.json"
[[mixins]]
config = "fogoverrides-common.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

displayTest="IGNORE_ALL_VERSION"

[[dependencies.fogoverrides]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_major_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_major_version},)"
ordering = "AFTER"
side = "BOTH"