modLoader = "javafml"
loaderVersion = "[51,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "fogoverrides"
version = "${version}"
displayName = "Fog Overrides"
authors = "fabbe50"
description = '''
Mod to make fog do what you want.
'''
#logoFile = ""

[[dependencies.fogoverrides]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"