modLoader = "javafml"
loaderVersion = "${loader_version_range}"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "fogoverrides"
version = "${version}"
displayName = "Fog Overrides"
authors = "fabbe50"
description = '''
Mod to make fog do what you want.
'''
#logoFile = ""

[[mixins]]
config = "fogoverrides.mixins.json"
[[mixins]]
config = "fogoverrides-common.mixins.json"

[[dependencies.fogoverrides]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fogoverrides]]
modId = "cloth_config"
type = "required"
versionRange = "[15,)"
ordering = "AFTER"
side = "CLIENT"